name: Generate Images

on:
  push:
    branches: [master]
  workflow_dispatch: # Manual trigger

jobs:
  generate_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install python dependencies
        run: pip install lupa
      - name: Install lpm
        run: wget https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/latest/lpm.x86_64-linux -O ./lpm-latest && chmod +x ./lpm-latest
      - name: remove colors
        run: rm -rf ./colors
      - name: remove colors
        run: mkdir ./colors
      - name: Generate lua files inside the directory parsers
        run: ./lpm-latest --userdir ./colors color install '*'
      - name: Rename it
        run: mv colors/colors colors/src
      - name: Make the images directory for the python's output
        run: mkdir ./colors/robotGeneratedScreenshots
      - name: Make the images directory for the python's output
        run: mkdir ./colors/robotGeneratedPreviewColors
      - name: Call python code
        run: python3 ./robots/create_preview_screenshots.py
      - name: Generate table with `lpm`
        run: ./lpm-latest exec robots/make_preview_image.lua colors/src/*
      - name: Generate lua files inside the directory parsers
        run: yes y | ./lpm-latest --userdir ./plugins plugin install '*'
      - name: Rename it
        run: mv plugins/plugins plugins/src
      - name: Clean up lpm-latest executable
        run: rm ./lpm-latest
      - name: Clean up lpm directorie
        run: rm -rf ./colors/lpm
      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "<>"
      - name: pull
        run: git pull
      - name: Git add
        run: git add .
      - name: Commit images
        run: git commit -m '[CI] Updated images'
      - name: Push changes
        run: git push